apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-spring-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-spring-demo
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/jasonchiu17/tap-spring-demo
      ref:
        branch: master
